[project]
name = "yolo-coreml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coremltools>=9.0",
    "matplotlib>=3.10.8",
    "ultralytics>=8.4.5",
]
